import type { Metadata } from 'next'
import { Noto_Sans, Noto_Sans_JP } from 'next/font/google'
import './globals.css'

const notoSansJP = Noto_Sans_JP({
  variable: '--font-note-sans-jp',
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
})

const notoSans = Noto_Sans({
  variable: '--font-note-sans',
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJP.variable} ${notoSans.variable} antialiased`}>{children}</body>
    </html>
  )
}
